---
kind: pipeline
type: kubernetes
name: default

steps:
- name: authenticate
  image: robertstettner/drone-mvn-auth
  settings:
    debug: true
    servers:
      from_secret: maven_servers

- name: debug
  image: ghcr.io/haraldkoch/dnstools:latest
  commands:
    - cat settings.xml

