---
kind: pipeline
type: kubernetes
name: default

steps:
- name: authenticate
  image: robertstettner/drone-mvn-auth
  settings:
    debug: true
    servers:
      from_secret: maven_servers

- name: debug
  image: alpine:3.14
  commands:
    - cat settings.xml

