---
kind: pipeline
type: kubernetes
name: default

steps:
- name: authenticate
  image: robertstettner/drone-mvn-auth
  settings:
    servers:
      from_secret: maven_servers

- name: debug
  image: alpine:latest
  commands:
    - pwd
    - cat .m2/settings.xml
    - cat ~/.m2/settings.xml

